// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TouristGuideWeb.Data;

#nullable disable

namespace TouristGuideWeb.Migrations
{
    [DbContext(typeof(TouristDbContext))]
    partial class TouristDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TouristGuideWeb.Models.Attraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("History")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TicketPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkingHours")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Attractions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "Главная площадь Москвы, включена в список Всемирного наследия ЮНЕСКО.",
                            History = "Красная площадь — сердце Москвы и всей России. На протяжении веков здесь проходили важнейшие исторические события. В XVII веке площадь стала главным торговым центром города.",
                            ImageUrl = "/images/red_square.jpg",
                            Name = "Красная площадь",
                            TicketPrice = 0m,
                            WorkingHours = "Круглосуточно"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Description = "Древнейшая часть Москвы, резиденция Президента России.",
                            History = "Кремль — древнейшая часть Москвы, впервые упоминается в 1156 году. На территории Кремля находятся древнейшие храмы и дворцы, соборы и музеи.",
                            ImageUrl = "/images/kremlin.jpg",
                            Name = "Московский Кремль",
                            TicketPrice = 700m,
                            WorkingHours = "10:00-18:00"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            Description = "Кафедральный собор Русской Православной Церкви.",
                            History = "Храм Христа Спасителя был заложен в 1839 году в честь победы в Отечественной войне 1812 года. Разрушен в 1931 году и восстановлен в 1994-2000 годах.",
                            ImageUrl = "/images/christ_savior.jpg",
                            Name = "Храм Христа Спасителя",
                            TicketPrice = 0m,
                            WorkingHours = "08:00-20:00"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Description = "Один из крупнейших музеев мира, государственный музей искусств.",
                            History = "Эрмитаж основан Екатериной II в 1764 году. Коллекция музея насчитывает более 3 миллионов произведений искусства и памятников мировой культуры.",
                            ImageUrl = "/images/hermitage.jpg",
                            Name = "Эрмитаж",
                            TicketPrice = 400m,
                            WorkingHours = "10:30-18:00"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 2,
                            Description = "Главная площадь Санкт-Петербурга, архитектурный ансамбль.",
                            History = "Дворцовая площадь — главная площадь Санкт-Петербурга, сформировавшаяся в XVIII-XIX веках. На площади находится Зимний дворец, Александровская колонна и другие памятники архитектуры.",
                            ImageUrl = "/images/palace_square.jpg",
                            Name = "Дворцовая площадь",
                            TicketPrice = 0m,
                            WorkingHours = "Круглосуточно"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 2,
                            Description = "Крупнейший собор Санкт-Петербурга, выдающийся памятник архитектуры.",
                            History = "Исаакиевский собор строился с 1818 по 1858 год. Собор является одним из самых высоких купольных сооружений в мире.",
                            ImageUrl = "/images/isaac.jpg",
                            Name = "Исаакиевский собор",
                            TicketPrice = 350m,
                            WorkingHours = "10:00-18:00"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 3,
                            Description = "Древнейшая часть Казани, объект Всемирного наследия ЮНЕСКО.",
                            History = "Казанский кремль — древнейшая часть города, основан в XI веке. С 2000 года включён в список Всемирного наследия ЮНЕСКО как уникальный образец культурного наследия народов России.",
                            ImageUrl = "/images/kazan_kremlin.jpg",
                            Name = "Казанский кремль",
                            TicketPrice = 0m,
                            WorkingHours = "06:00-22:00"
                        },
                        new
                        {
                            Id = 8,
                            CityId = 3,
                            Description = "Главная мечеть Татарстана, символ Казани.",
                            History = "Мечеть Кул-Шариф была построена в XVI веке и разрушена в 1552 году при осаде Казани. Современная мечеть восстановлена в 2005 году.",
                            ImageUrl = "/images/kul_sharif.jpg",
                            Name = "Мечеть Кул-Шариф",
                            TicketPrice = 0m,
                            WorkingHours = "08:00-20:00"
                        },
                        new
                        {
                            Id = 9,
                            CityId = 4,
                            Description = "Вантовый мост через пролив Босфор Восточный, один из крупнейших в мире.",
                            History = "Русский мост построен к саммиту АТЭС 2012 года. Мост связал остров Русский с материковой частью Владивостока.",
                            ImageUrl = "/images/russian_bridge.jpg",
                            Name = "Русский мост",
                            TicketPrice = 0m,
                            WorkingHours = "Круглосуточно"
                        },
                        new
                        {
                            Id = 10,
                            CityId = 4,
                            Description = "Мощная система оборонительных сооружений, одна из сильнейших в мире.",
                            History = "Владивостокская крепость строилась с 1879 по 1918 год. Крепость считалась одной из самых мощных в мире и включала более 100 фортов и батарей.",
                            ImageUrl = "/images/fort.jpg",
                            Name = "Владивостокская крепость",
                            TicketPrice = 100m,
                            WorkingHours = "10:00-18:00"
                        });
                });

            modelBuilder.Entity("TouristGuideWeb.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoatOfArmsUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("History")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Population")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoatOfArmsUrl = "/images/Coat_of_arms_of_Moscow.svg.png",
                            Description = "Столица России, крупнейший город страны.",
                            History = "Москва — один из древнейших городов России. Первое упоминание о Москве встречается в летописи 1147 года. Город стал столицей Великого княжества Московского в XV веке и остаётся столицей России по сей день.",
                            ImageUrl = "/images/moscow.jpg",
                            Name = "Москва",
                            Population = 12537954,
                            Region = "Центральный федеральный округ"
                        },
                        new
                        {
                            Id = 2,
                            CoatOfArmsUrl = "/images/images.png",
                            Description = "Культурная столица России, город на Неве.",
                            History = "Санкт-Петербург основан Петром I в 1703 году. Город был столицей Российской империи до 1918 года. Известен своей архитектурой, музеями и культурным наследием.",
                            ImageUrl = "/images/4646af3618e50dcf2cbddfb325446f11.webp",
                            Name = "Санкт-Петербург",
                            Population = 5383890,
                            Region = "Северо-Западный федеральный округ"
                        },
                        new
                        {
                            Id = 3,
                            CoatOfArmsUrl = "/images/Снимок экрана 2026-05-05 в 10.23.55 AM.png",
                            Description = "Столица Татарстана, город с богатой историей.",
                            History = "Казань — один из древнейших городов России, основанный в 1005 году. В 1556 году город вошёл в состав России. Сегодня это крупный культурный и образовательный центр.",
                            ImageUrl = "/images/324671d930c2c6b747910a712de92692.webp",
                            Name = "Казань",
                            Population = 1259173,
                            Region = "Приволжский федеральный округ"
                        },
                        new
                        {
                            Id = 4,
                            CoatOfArmsUrl = "/images/Coat_of_Arms_of_Vladivostok.svg.png",
                            Description = "Город на Тихом океане, крупнейший порт Дальнего Востока.",
                            History = "Владивосток основан в 1859 году как военный пост. Город стал важнейшей военно-морской базой России на Тихом океане и крупнейшим портом Дальнего Востока.",
                            ImageUrl = "/images/vladivostok.jpg",
                            Name = "Владивосток",
                            Population = 604901,
                            Region = "Дальневосточный федеральный округ"
                        });
                });

            modelBuilder.Entity("TouristGuideWeb.Models.Attraction", b =>
                {
                    b.HasOne("TouristGuideWeb.Models.City", "City")
                        .WithMany("Attractions")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("TouristGuideWeb.Models.City", b =>
                {
                    b.Navigation("Attractions");
                });
#pragma warning restore 612, 618
        }
    }
}
